import React from 'react';
import { GeneratedRoutine, ComedyBit } from '../types';
import { Button } from './Button';

interface RoutineDisplayProps {
  routine: GeneratedRoutine;
  onReset: () => void;
}

const BitCard: React.FC<{ bit: ComedyBit; index: number }> = ({ bit, index }) => (
  <div className="bg-slate-800 rounded-xl p-6 border border-slate-700 hover:border-amber-500/50 transition-colors duration-300 shadow-lg relative overflow-hidden group">
    <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
        <span className="text-6xl font-black text-amber-500">#{index + 1}</span>
    </div>
    
    <div className="relative z-10">
      <h3 className="text-xl font-bold text-amber-400 mb-4 font-mono uppercase tracking-wide">{bit.title}</h3>
      
      <div className="space-y-4">
        <div>
            <span className="text-xs font-bold text-slate-500 uppercase tracking-wider block mb-1">Setup</span>
            <p className="text-slate-200 leading-relaxed text-lg">{bit.setup}</p>
        </div>
        
        <div className="bg-slate-900/50 p-4 rounded-lg border-l-4 border-amber-500">
            <span className="text-xs font-bold text-amber-600 uppercase tracking-wider block mb-1">Punchline</span>
            <p className="text-white text-xl font-bold italic">"{bit.punchline}"</p>
        </div>

        {(bit.actOut || bit.coachingTip) && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4 pt-4 border-t border-slate-700/50">
                {bit.actOut && (
                    <div>
                        <span className="text-xs font-bold text-purple-400 uppercase tracking-wider block mb-1">🎭 Act Out</span>
                        <p className="text-slate-400 text-sm italic">{bit.actOut}</p>
                    </div>
                )}
                {bit.coachingTip && (
                    <div>
                        <span className="text-xs font-bold text-emerald-400 uppercase tracking-wider block mb-1">💡 Coach's Note</span>
                        <p className="text-slate-400 text-sm">{bit.coachingTip}</p>
                    </div>
                )}
            </div>
        )}
      </div>
    </div>
  </div>
);

export const RoutineDisplay: React.FC<RoutineDisplayProps> = ({ routine, onReset }) => {
  
  const handleExport = () => {
    const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PunchlinePro Routine</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; max-width: 800px; margin: 40px auto; line-height: 1.6; padding: 20px; background: #f8fafc; color: #1e293b; }
        h1 { color: #0f172a; text-align: center; margin-bottom: 40px; border-bottom: 2px solid #e2e8f0; padding-bottom: 20px; }
        .section { background: white; padding: 30px; margin-bottom: 25px; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); border: 1px solid #e2e8f0; page-break-inside: avoid; }
        .opener { border-left: 6px solid #6366f1; background: #eef2ff; }
        .closer { border-left: 6px solid #ef4444; background: #fef2f2; }
        .bit { border-left: 6px solid #f59e0b; }
        h3 { margin-top: 0; color: #b45309; font-size: 1.2em; text-transform: uppercase; letter-spacing: 0.05em; }
        .label { font-weight: 700; font-size: 0.75em; text-transform: uppercase; color: #64748b; display: block; margin-bottom: 4px; letter-spacing: 0.05em; }
        .punchline { font-size: 1.2em; font-weight: 700; color: #0f172a; margin: 15px 0; font-style: italic; padding: 15px; background: #fffbeb; border-radius: 6px; }
        .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-top: 20px; padding-top: 20px; border-top: 1px solid #f1f5f9; }
        .note { font-size: 0.9em; }
        .act-out-label { color: #7c3aed; }
        .coach-label { color: #059669; }
        @media print {
            body { background: white; max-width: 100%; margin: 0; }
            .section { box-shadow: none; border: 1px solid #ccc; }
        }
    </style>
</head>
<body>
    <h1>My Tight 10 - Generated by PunchlinePro</h1>

    <div class="section opener">
        <span class="label" style="color: #4f46e5;">The Opener</span>
        <p style="font-size: 1.2em; font-weight: 500;">"${routine.opener}"</p>
    </div>

    ${routine.bits.map((bit, i) => `
    <div class="section bit">
        <h3>${i + 1}. ${bit.title}</h3>
        <div style="margin-bottom: 15px;">
            <span class="label">Setup</span>
            <p>${bit.setup}</p>
        </div>
        <div>
            <span class="label">Punchline</span>
            <div class="punchline">"${bit.punchline}"</div>
        </div>
        ${(bit.actOut || bit.coachingTip) ? `
        <div class="grid">
            ${bit.actOut ? `
            <div class="note">
                <span class="label act-out-label">🎭 Act Out</span>
                ${bit.actOut}
            </div>` : '<div></div>'}
            ${bit.coachingTip ? `
            <div class="note">
                <span class="label coach-label">💡 Coach's Note</span>
                ${bit.coachingTip}
            </div>` : '<div></div>'}
        </div>` : ''}
    </div>
    `).join('')}

    <div class="section closer">
        <span class="label" style="color: #dc2626;">The Closer</span>
        <p style="font-size: 1.2em; font-weight: 500;">"${routine.closer}"</p>
    </div>
    
    <div style="text-align: center; margin-top: 40px; color: #94a3b8; font-size: 0.8em;">
        Generated by PunchlinePro
    </div>
</body>
</html>`;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'punchline-pro-routine.html';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-4xl mx-auto space-y-12 animate-fade-in">
      
      <div className="text-center space-y-4">
        <div className="inline-block px-4 py-1 rounded-full bg-amber-500/10 text-amber-500 font-mono text-sm border border-amber-500/20">
            GENERATED SET
        </div>
        <h2 className="text-4xl md:text-5xl font-bold text-white">Your Tight 10</h2>
        <p className="text-slate-400 max-w-lg mx-auto">
            Here is your structured routine. Practice the timing, lean into the act-outs, and remember: confidence is key.
        </p>
      </div>

      {/* Opener */}
      <div className="bg-gradient-to-r from-slate-800 to-slate-900 p-8 rounded-2xl border border-indigo-500/30 shadow-2xl relative overflow-hidden">
        <div className="absolute top-0 left-0 w-1 h-full bg-indigo-500"></div>
        <span className="text-indigo-400 font-bold tracking-widest text-sm uppercase mb-2 block">The Opener</span>
        <p className="text-2xl text-white font-medium">"{routine.opener}"</p>
      </div>

      {/* The Bits */}
      <div className="grid grid-cols-1 gap-8">
        {routine.bits.map((bit, idx) => (
          <BitCard key={bit.id || idx} bit={bit} index={idx} />
        ))}
      </div>

      {/* Closer */}
      <div className="bg-gradient-to-r from-slate-800 to-slate-900 p-8 rounded-2xl border border-red-500/30 shadow-2xl relative overflow-hidden">
        <div className="absolute top-0 left-0 w-1 h-full bg-red-500"></div>
        <span className="text-red-400 font-bold tracking-widest text-sm uppercase mb-2 block">The Closer</span>
        <p className="text-2xl text-white font-medium">"{routine.closer}"</p>
      </div>

      <div className="flex flex-col sm:flex-row justify-center items-center gap-4 pt-8 pb-20">
        <Button variant="outline" onClick={handleExport} className="w-full sm:w-auto flex items-center gap-2">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Export HTML
        </Button>
        <Button variant="secondary" onClick={onReset} className="w-full sm:w-auto">
            Start A New Set
        </Button>
      </div>
    </div>
  );
};
